### ISSUE TITLE
AdvancedHunt 3.1.0 Failed to download plugin

### ISSUE THREAD

**Issue by pjindras** [TheRedEnd2000/AdvancedHunt#1]
<html>
<body>

[05:01:06] [Server thread/ERROR]: [AdvancedHunt] Failed to download plugin
--
1271 | java.nio.file.NoSuchFileException: plugins/update/NBTAPI-2.14.0.jar
1272 | at java.base/sun.nio.fs.UnixException.translateToIOException(Unknown Source) ~[?:?]
1273 | at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source) ~[?:?]
1274 | at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source) ~[?:?]
1275 | at java.base/sun.nio.fs.UnixFileSystem.move(Unknown Source) ~[?:?]
1276 | at java.base/sun.nio.fs.UnixFileSystemProvider.move(Unknown Source) ~[?:?]
1277 | at java.base/java.nio.file.Files.move(Unknown Source) ~[?:?]
1278 | at AdvancedEggHunt-3.1.0.jar/de.theredend2000.advancedhunt.util.PluginDownloader.moveOldVersion(PluginDownloader.java:434) ~[AdvancedEggHunt-3.1.0.jar:?]
1279 | at AdvancedEggHunt-3.1.0.jar/de.theredend2000.advancedhunt.util.PluginDownloader.downloadPlugin(PluginDownloader.java:79) ~[AdvancedEggHunt-3.1.0.jar:?]
1280 | at AdvancedEggHunt-3.1.0.jar/de.theredend2000.advancedhunt.Main.setupAutoUpdating(Main.java:317) ~[AdvancedEggHunt-3.1.0.jar:?]
1281 | at AdvancedEggHunt-3.1.0.jar/de.theredend2000.advancedhunt.Main.onEnable(Main.java:91) ~[AdvancedEggHunt-3.1.0.jar:?]
1282 | at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
1283 | at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[leaf-1.21.1.jar:1.21.1-DEV-3842aa3]
1284 | at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[leaf-1.21.1.jar:1.21.1-DEV-3842aa3]
1285 | at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:519) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
1286 | at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:658) ~[leaf-1.21.1.jar:1.21.1-DEV-3842aa3]
1287 | at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:607) ~[leaf-1.21.1.jar:1.21.1-DEV-3842aa3]
1288 | at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:742) ~[leaf-1.21.1.jar:1.21.1-DEV-3842aa3]
1289 | at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:504) ~[leaf-1.21.1.jar:1.21.1-DEV-3842aa3]
1290 | at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:374) ~[leaf-1.21.1.jar:1.21.1-DEV-3842aa3]
1291 | at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1216) ~[leaf-1.21.1.jar:1.21.1-DEV-3842aa3]
1292 | at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[leaf-1.21.1.jar:1.21.1-DEV-3842aa3]
1293 | at java.base/java.lang.Thread.run(Unknown Source) ~[?:?]

</body>
</html>

**Comment by TheRedEnd2000** [comment]
check if the file does already exist in the OLD_PLUGINS folder

**Comment by PhantomLink** [comment]
It has been fixed in the latest version 3.1.1
